EpamTask5/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EpamTask5.Models;
using EpamTask4.Repository;
using System.Net.Http;

namespace EpamTask5.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        // GET: Manager
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Manager/Details/5
        [Ajax]
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var managerId = id ?? default(int);
            var manager = new ManagerRepository().GetById(managerId).Select(x => new Manager() { Id = x.Id, Name = x.ManagerName }).FirstOrDefault();
            if (manager == null)
            {
                return HttpNotFound();
            }
            return PartialView(manager);
        }

        // GET: Manager/Create
        [Ajax]
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Manager/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Ajax]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                var item = new EpamTask4.Manager() { Id = manager.Id, ManagerName = manager.Name };
                new ManagerRepository().Insert(item);
                return RedirectToAction("Index");
            }

            return View(manager);
        }

        [HttpGet]
        public ActionResult Denied()
        {
            return View();
        }

        [Ajax]
        [HttpGet]
        public ActionResult ManagerList()
        {
            var item = new ManagerRepository().GetAll().OrderBy(a=>a.ManagerName).Select(x => new Manager() { Id = x.Id, Name = x.ManagerName });
            return PartialView("_PartialManagerList", item);
        }

        // GET: Manager/Edit/5
        [Ajax]
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var managerId = id ?? default(int);

            var manager = new ManagerRepository().GetById(managerId).Select(x => new Manager() { Id = x.Id, Name = x.ManagerName }).FirstOrDefault();

            if (manager == null)
            {
                return HttpNotFound();
            }
            return PartialView(manager);
        }

        // POST: Manager/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                var item = new ManagerRepository().GetById(manager.Id).FirstOrDefault();
                if (item != null)
                {
                    item.ManagerName = manager.Name;
                    new ManagerRepository().Update(item);
                }
                return RedirectToAction("Index");
            }
            return PartialView(manager);
        }

        // GET: Manager/Delete/5

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var managerId = id ?? default(int);

            var manager = new ManagerRepository().GetById(managerId).Select(x => new Manager() { Id = x.Id, Name = x.ManagerName }).FirstOrDefault();

            if (manager == null)
            {
                return HttpNotFound();
            }

            return View(manager);
        }

        // POST: Manager/Delete/5
        [HttpPost, ActionName("Delete")]
       
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
                var item = new ManagerRepository().GetById(id).FirstOrDefault();
                new ManagerRepository().Remove(item);
           
            return RedirectToAction("Index");
        }

        [Ajax]
        public JsonResult GetChartData(int? id)
        {
            if (id == null)
            {
                var items = new ManagerRepository()
                    .GetAll()
                    .Select(m => new object[]
                    {
                        m.ManagerName,
                        new ManagerRepository()
                        .GetSumById(m.Id)
                    })
                    .ToArray();

                return Json(items, JsonRequestBehavior.AllowGet);
            }

            int idManager = id ?? default(int);

            var sales = new ManagerRepository()
                .GetSalesByManagerId(idManager)
                .OrderBy(s => s.SaleDate)
                .GroupBy(s => s.SaleDate.Date)
                .Select(d => new object[] { d.Key, d.Sum(s => s.Sum) })
                .ToArray();

            return Json(sales, JsonRequestBehavior.AllowGet);
        }
    }
}

EpamTask5/Controllers/SaleInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EpamTask5.Models;
using EpamTask4.Repository;

namespace EpamTask5.Controllers
{
    public class SaleInfoesController : Controller
    {
        // GET: SaleInfoes
       
        [HttpGet]
        public ActionResult Index()
        {
            var items = new SaleRepository()
                .GetAll()
                .Select(x => new SaleInfo()
                {
                    Id = x.Id,
                    Sum = x.Sum,
                    Date = x.SaleDate,
                    IdManager =(int)x.ID_Manager,
                    IdClient = (int)x.ID_Client,
                    IdProduct = (int)x.ID_Product
                }).ToArray();
            return View(items);
        }

    }
}

EpamTask5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/Scripts/jquery-1.10.2.js"></script>
    <script src="/Scripts/bootstrap-datepicker.js"></script>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EpamTask5", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator") )
                    {
                        <li>@Html.ActionLink("Managers", "Index", "Manager")</li>
                        <li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Sales", "Index", "SaleInfoes")</li>
                    }
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Task 5 - Robert Senkel</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>